### ISSUE TITLE
Update to HA

### ISSUE THREAD

**Issue by danielmbrown603** [rwoldberg/ldata-ha#19]
I noticed HA updated recently and implemented the stacked individual device view. Seems there is a discrepancy between the CT view and stacked view. For my setup, 85-90% of my electricity usage has a smart breaker, which means I'd expect the CT view to show slightly higher, however, it appears to be the opposite. For example, look at the difference during 1am. Any thoughts?

![image](https://github.com/rwoldberg/ldata-ha/assets/79930376/deec6caf-c83d-4bb3-8a79-e14302eef073)

**Comment by rwoldberg** [comment]
I don't know, and my home assistant database crashed so I can't look at my historical data.  But all of my breakers are smart breakers so I am not sure it would help anyway.

**Comment by danielmbrown603** [comment]
> I don't know, and my home assistant database crashed so I can't look at my historical data. But all of my breakers are smart breakers so I am not sure it would help anyway.

Well, that is what I am getting at. If I had all smart breakers, the discrepancy would be even greater. Looking at 1AM with the individual breakers adding up, its consumption is larger than what the CT is showing at 1AM. In my situation (not having all smart breakers), I'd expect the CT output to be the larger number and the individual breaker view to be smaller. When your database is fixed or populated again, curious if you notice this with your setup.

**Comment by rwoldberg** [comment]
I am seeing some very strange data in my history, so I don't think my historical data is accurate after my DB crash.  But I am not sure the CT data will ever match the total for the breakers simply because of how the data is gathered.  Since this integration is relying on the cloud and only polling one a minute that will introduce errors.   It is also possible that my code is not calculating the kilowatts used correctly.
