### ISSUE TITLE
Possible Calculation or Rounding Discrepancies

### ISSUE THREAD

**Issue by johnsoga** [rwoldberg/ldata-ha#24]
So admittedly I'm new to HA let alone this plugin for incorporating Leviton's data into HA Dashboards, that is to say I'm very open to I'm not doing something right.

What I noticed was there there were some discrepancies between the values MyLeviton was reporting for the and what this integration was showing in HA. I've not had it running very long and from what I can see the discrepancy is less than .5/kwh. So arguably it could be considered negligible. I'm just not certain if this was expected or not. There was one large discrepancy on the first day that I added the plugin to my HA of about 5.79/kwh I don't know if this was just a difference due to something on its initial digest or idk something else. Open to any thoughts or feedback

![Screenshot 2024-11-11 at 10 38 24 PM](https://github.com/user-attachments/assets/3961fedd-2fc3-4b86-88aa-1b1bd88b08a8)

![Screenshot 2024-11-11 at 10 39 00 PM](https://github.com/user-attachments/assets/86be3863-602b-4368-aaf3-c8df8fb74ff8)

**Comment by rwoldberg** [comment]
I am not sure how leviton does their calculate, the way this integration does it is this: the integration pulls the current usage data from leviton every 60 seconds then takes the average between the last two reading and adds that to the usage for each breaker.   It does not use the consumption data provided by leviton because I found, at least for mine, that data was bad.  So there may be differences if leviton has access to data more often than 60 seconds, which I suspect they do.  There is a configuration setting for the sample seconds you can change that to a lower value, the lowest you can set it is 30 seconds.  I defaulted it to 60 so levitons servers don't get overloaded.  If that happens they could shut down access to the API.

**Comment by johnsoga** [comment]
That sounds like a reasonable answer for sure. Admittedly I would hope they've designed their system to be able to handle requests more frequently than every 60 seconds, but best to be safe rather than get banned. Would be interesting to capture some packets from this with wireshark as presumably that would give an idea of how often they're polling these devices. But I got my answer on how at least how you're doing it. Thank you!

**Comment by rwoldberg** [comment]
There are two different things going on.  You have the local device, the LDATA or LWHEM that is querying data from the breakers and CTs and then sending that data to leviton's severs at some interval.  Then there is the web app or phone app that queries the collected data from leviton.  That is the API that the home assistant integration is using.  Most of the time the web app or phone app is not running so very few calls will be made to the API.  With this integration however, this API is now being called all the time.  I would really like leviton to have a local API to the LDATA and LWHEM, but so far they have refused to open that up.
